#!/bin/bash
# возвращает уровень освещенности 0 до 1

# прессет камеры - подберите их нужным образом
v4l2-ctl -d /dev/video2 -c auto_exposure=1 # ручной режим выдержки
v4l2-ctl -d /dev/video2 -c exposure_time_absolute=166 # установить выдержку 32
v4l2-ctl -d /dev/video2 -c gain=19 # установить усиление 19

ffmpeg -f v4l2 -i /dev/video2 -frames 1 -y /tmp/tmp.jpg > /dev/null 2> /dev/null
# средняч освещенность
mean=$(convert /tmp/tmp.jpg -colorspace Gray -format "%[fx:mean]" info:)
mean=$(awk -v val="$mean" 'BEGIN {printf "%.8f", val}')
echo $mean;